In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",encoding='latin-1')
data

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
#removing unwanted columns
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1,inplace=True)
data

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
data.shape

(5572, 2)

#### Spliting the data

In [5]:
#split the data --> 80% to training data and 20% testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data.v2,data.v1,test_size=0.2)

In [6]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4457,)
(1115,)
(4457,)
(1115,)


#### Initialising Count Vectorizer

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
#creating object for Count Vectorizer
count_vect=CountVectorizer()

### Generate word count for document

In [8]:
word_count_vector=count_vect.fit(X_train)
print(word_count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [9]:
#to get feature names
word_count_vector.get_feature_names()

['00',
 '000',
 '008704050406',
 '0089',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '07732584351',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808726822',
 '07815296484',
 '07821230901',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '087006211701

In [10]:
#transforming the data 
doc_array=word_count_vector.transform(X_train)
doc_array

<4457x7598 sparse matrix of type '<class 'numpy.int64'>'
	with 58811 stored elements in Compressed Sparse Row format>

In [11]:
#Converting to an array
doc_array=word_count_vector.transform(X_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
#Converting to an dataframe
dataf=pd.DataFrame(doc_array,columns=word_count_vector.get_feature_names())
#pd.set_option('display.max_rows',None #for displayig all rows
dataf

00  000  008704050406  0089  01223585236  01223585334  0125698789  02  \
0      0    0             0     0            0            0           0   0   
1      0    0             0     0            0            0           0   0   
2      0    0             0     0            0            0           0   0   
3      0    0             0     0            0            0           0   0   
4      0    0             0     0            0            0           0   0   
...   ..  ...           ...   ...          ...          ...         ...  ..   
4452   0    0             0     0            0            0           0   0   
4453   0    0             0     0            0            0           0   0   
4454   0    0             0     0            0            0           0   0   
4455   0    0             0     0            0            0           0   0   
4456   0    0             0     0            0            0           0   0   

      02072069400  02073162414  ...  ìï  û_  û_thanks  ûªm  ûªt  ûªve  ûï  \
0               0            0  ...   1   0         0    0    0     0   0   
1               0            0  ...   0   0         0    0    0     0   0   
2               0            0  ...   0   0         0    0    0     0   0   
3               0            0  ...   0   0         0    0    0     0   0   
4               0            0  ...   0   0         0    0    0     0   0   
...           ...          ...  ...  ..  ..       ...  ...  ...   ...  ..   
4452            0            0  ...   0   0         0    0    0     0   0   
4453            0            0  ...   0   0         0    0    0     0   0   
4454            0            0  ...   0   0         0    0    0     0   0   
4455            0            0  ...   0   0         0    0    0     0   0   
4456            0            0  ...   0   0         0    0    0     0   0   

      ûïharry  ûò  ûówell  
0           0   0       0  
1           0   0       0  
2           0   0       0  
3           0   0       0  
4           0   0       0  
...       ...  ..     ...  
4452        0   0       0  
4453        0   0       0  
4454        0   0       0  
4455        0   0       0  
4456        0   0       0  

[4457 rows x 7598 columns]

In [25]:
#TIDF Vectorizer
#import TIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
# Initialize and object for the TFIDF Vectorizer
tfidf = TfidfVectorizer()

In [26]:
#apply the tidf vectorizer to the data(X_train)
X_train_transformed = tfidf.fit_transform(X_train)
X_train_transformed

<4457x7598 sparse matrix of type '<class 'numpy.float64'>'
	with 58811 stored elements in Compressed Sparse Row format>

#### Why fit_transform is performed only on training data?

Now if we specifically talk about CountVectorizer, then consider the following example, let your training data have the following 3 sentences:

Dog is black.

Sky is blue.

Dog is dancing.
Now the vocabulary set for this will be {Dog, is, black, sky, blue, dancing}. Now the algorithm that you will train will try to learn rules based on the count of these 6 vocabulary terms. So your features will be vectors of length 6.

Now if the test set is as follows:

Dog is white.

Sky is black.

Now if you use the test data for fit_transform your vocabulary will look like {Dog, white, is, Sky, black}. So here your each document will be represented by a vector of length 5 denoting the counts of each of these terms. Now, this will be like comparing apples with oranges. You learn rules for counts of the previous vocabulary and those rules can not be applied to this vocabulary. This is the reason why you only fit on the training data.


In [27]:
X_test_transformed = tfidf.transform(X_test)
X_test_transformed

<1115x7598 sparse matrix of type '<class 'numpy.float64'>'
	with 13947 stored elements in Compressed Sparse Row format>

In [28]:
#Feature Names
tfidf.get_feature_names()


['00',
 '000',
 '008704050406',
 '0089',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '07732584351',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808726822',
 '07815296484',
 '07821230901',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '087006211701

#### Vocabulary Position

In [17]:
tfidf.vocabulary_

{'yes': 3647,
 'gauti': 1405,
 'and': 418,
 'sehwag': 2833,
 'out': 2377,
 'of': 2316,
 'odi': 2315,
 'series': 2857,
 'are': 458,
 'you': 3658,
 'driving': 1122,
 'or': 2359,
 'training': 3312,
 'no': 2273,
 'gifts': 1432,
 'trying': 3335,
 'to': 3274,
 'get': 1423,
 'me': 2058,
 'throw': 3246,
 'myself': 2206,
 'off': 2318,
 'cliff': 833,
 'something': 2993,
 'really': 2658,
 'do': 1079,
 'hope': 1613,
 'the': 3216,
 'work': 3596,
 'doesnt': 1086,
 'stressful': 3084,
 'have': 1544,
 'gr8': 1472,
 'day': 998,
 'today': 3278,
 'iz': 1748,
 'yellow': 3643,
 'rose': 2758,
 'if': 1669,
 'love': 1967,
 'my': 2205,
 'frndship': 1378,
 'give': 1440,
 'misscall': 2112,
 'amp': 412,
 'send': 2845,
 'this': 3236,
 'ur': 3396,
 'frndz': 1379,
 'see': 2826,
 'how': 1628,
 'many': 2025,
 'miss': 2111,
 'calls': 720,
 '6missed': 251,
 'marry': 2037,
 'lover': 1970,
 'when': 3534,
 'we': 3502,
 'finish': 1316,
 'loads': 1932,
 'loans': 1934,
 'pay': 2427,
 'india': 1692,
 'win': 3561,
 'level': 1896

In [29]:
#Idf of terms
tfidf.idf_

array([7.09987042, 6.22440168, 8.70930833, ..., 8.70930833, 7.61069604,
       8.70930833])

In [30]:
#Applying Naive bayes algorithm
from sklearn.naive_bayes import BernoulliNB
#creating object for BerNB
model_BernNB = BernoulliNB()

In [31]:
# Applying the Algorithm to the data
# ObjectName.fit(Input, Output)
model_BernNB.fit(X_train_transformed, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [32]:
#prediction on test data
#Syntax:Objectname.predict(Inputvalues)
y_test_pred = model_BernNB.predict(X_test_transformed)

In [33]:
# Compare the actual values(y_test) with predicted values(y_test_pred)
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test, y_test_pred)

array([[971,   0],
       [ 18, 126]], dtype=int64)

In [34]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       971
        spam       1.00      0.88      0.93       144

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [35]:
# Test a single message--> Spam or Ham
new_message = pd.Series('Last few days to collect the free\
                     entry passes with 40% discount')

# Calculate tfidf values for the new message
new_message_transformed = tfidf.transform(new_message)

In [36]:
# Predict the new message
model_BernNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')