## different ways for using predefined modules

In [5]:
import string
string.digits

'0123456789'

In [15]:
import string as s
s.digits

'0123456789'

In [17]:
from string import digits,punctuation
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [18]:
from string import *
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


# user defined modules

In [7]:
import operations as o
o.wish("user")
o.result

hello user


'True'

# Predefined 

In [13]:
import math
def Area(r):
    return math.pi*r*r
Area(7)

153.93804002589985

In [20]:
import statistics as s1
l1=list(range(1,21))
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [27]:
print(s1.mean(l1))
print(sum(l1)/len(l1))

10.5
10.5


In [35]:
l2=[1,2,3,42,333,23,22,2,2]
print(s1.mode(l2))

2


In [36]:
s1.stdev(l2)

107.90247654453741

In [39]:
s1.variance(l1)

35.0

# random

In [44]:
import random
print(random.randint(1,10))
print(random.choice(l1))
print(random.random())

5
2
0.3678022651061521


In [50]:
print(random.choice(l1))
print(random.choices(l1,k=2))

19
[19, 1]


# Os


In [51]:
import os
os.mkdir("a")

In [53]:
os.getcwd()

'C:\\Users\\karthik\\Adv-prog\\Untitled Folder'

In [54]:
os.listdir()

['.ipynb_checkpoints',
 '1June20 Assignment.ipynb',
 '1June2020.ipynb',
 '28may2020.ipynb',
 '29may2020.ipynb',
 '2June2020 Assignment.ipynb',
 '2June2020.ipynb',
 '3.txt',
 '30May2020.ipynb',
 '30May2020Assignment.ipynb',
 '3june2020.ipynb',
 'a',
 'a.txt',
 'Assignment-28may2020.ipynb',
 'Assignment29May2020.ipynb',
 'h1.txt',
 'hello.c',
 'hello.txt',
 'operations.py',
 '__pycache__']

In [62]:
os.chdir('C:\\Users\\karthik\\Adv-prog\\Untitled Folder')

In [63]:
os.getcwd()

'C:\\Users\\karthik\\Adv-prog\\Untitled Folder'

# Numpy Operations

In [65]:
import numpy as np
l1=[1,2,3,4,5]
arr=np.array(l1)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [66]:
l2=list(range(1,11))
l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [67]:
arr2=np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
#Less memory
import sys
size = 1000
list1 = list(range(size))
print(sys.getsizeof(list1[0])*size)
arr1 = np.arange(1000)
print(arr1.itemsize * arr1.size)

24000
4000


In [70]:
#Numpy Arrays are Faster
import time
size = 20000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [x+y for x,y in zip(list1,list2)]
print("Time took for python list: ",time.time()-start)

arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result = arr1 + arr2
print("Time took for Numpy array: ",time.time()-start)

Time took for python list:  0.0019812583923339844
Time took for Numpy array:  0.0009765625


In [71]:
l1 = [1,2,3,4,5]
l2 = [10,11,12,23,14]
result = [x+y for x,y in zip(l1,l2)]
result

[11, 13, 15, 27, 19]

In [72]:
#Numpy arrays are convenient
a1 = np.array(l1)
a2 = np.array(l2)
a1 + a2


array([11, 13, 15, 27, 19])