In [ ]:
#Using Random()

In [28]:
from numpy import random
print(random.randint(1,100)) #integers
print(random.rand(1)) #float

13
[0.66698993]


In [23]:
#creating n dimensional array 
print(random.randint(100,size=(10)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[68 16 31  4 22 79 46 40  4 45]
[[59  8 42  0]
 [93 21 88  7]
 [69 93 82 59]]
[[[45 49]
  [69 67]
  [94 80]
  [43 75]]

 [[29  4]
  [94 57]
  [69 63]
  [67  0]]

 [[76 91]
  [94 84]
  [ 1 29]
  [92 25]]]


In [26]:
#creating n dimensional array with float values
print(random.rand())
print(random.rand(3))
print(random.rand(3,4))

0.10927379966211703
[0.57098295 0.28394238 0.36947264]
[[0.18470092 0.21255667 0.99653842 0.04089418]
 [0.56200814 0.14656304 0.21685197 0.58147151]
 [0.77624382 0.40846922 0.79663541 0.33546979]]


In [30]:
a=random.randint(100,size=(3,2)).ravel()
a

array([36, 73, 21, 86, 39, 93])

In [31]:
#single element will be selected
random.choice(a)

93

In [34]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[5, 4, 4, 5],
       [1, 4, 3, 5],
       [1, 5, 2, 2],
       [4, 2, 2, 2]])

## pandas


## creating data frames
### 1.using two dictionaries

In [52]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4}
dict2={'a':5,'b':6,'c':7,'d':8,'e':10}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data,dtype=np.int32) #nan meansNaN - Not a NUmber
df

First  Second
a    1.0       5
b    2.0       6
c    3.0       7
d    4.0       8
e    NaN      10

In [54]:
#simple dictionary --->Data Frame
d1={"Name":["Sathvik","Rithwik","Sahith","Reddy","Vinay","Karthikeya","Siddu","Dheeraj"],"Address":["Hyd","Mbnr","Knr","Kun","Bvm","Hyd","Hyd","Hyd"]}
df=pd.DataFrame(d1)
df


Name Address
0     Sathvik     Hyd
1     Rithwik    Mbnr
2      Sahith     Knr
3       Reddy     Kun
4       Vinay     Bvm
5  Karthikeya     Hyd
6       Siddu     Hyd
7     Dheeraj     Hyd

## Using series

In [56]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([1.2,1.3,1.4,2.5,2.3,4.1,23.2,12.4,21.3,23.6])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"Column1":s1,"Column2":s2,"Column3":s3}
df3=pd.DataFrame(data)
df3

Column1  Column2 Column3
0        1      1.2       a
1        2      1.3       b
2        3      1.4       c
3        4      2.5       d
4        5      2.3       e
5        6      4.1       f
6        7     23.2       g
7        8     12.4       h
8        9     21.3       i
9       10     23.6       j

In [59]:
#single column data extraction
df3["Column3"]

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
Name: Column3, dtype: object

In [63]:
df3[["Column3","Column2"]]

Column3  Column2
0       a      1.2
1       b      1.3
2       c      1.4
3       d      2.5
4       e      2.3
5       f      4.1
6       g     23.2
7       h     12.4
8       i     21.3
9       j     23.6

## Selecting data from dataframe set
    -loc
    -iloc

In [66]:
df3["Column2"]

0     1.2
1     1.3
2     1.4
3     2.5
4     2.3
5     4.1
6    23.2
7    12.4
8    21.3
9    23.6
Name: Column2, dtype: float64

In [67]:
df3[["Column3","Column2"]]

Column3  Column2
0       a      1.2
1       b      1.3
2       c      1.4
3       d      2.5
4       e      2.3
5       f      4.1
6       g     23.2
7       h     12.4
8       i     21.3
9       j     23.6

In [68]:
# single column
df3.loc[:,"Column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Column1, dtype: int64

In [72]:
# extracting multiple column values
df3.loc[0:5,["Column1","Column2"]]

Column1  Column2
0        1      1.2
1        2      1.3
2        3      1.4
3        4      2.5
4        5      2.3
5        6      4.1

In [73]:
df3.loc[0:5,["Column1"]]

Column1
0        1
1        2
2        3
3        4
4        5
5        6

In [75]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  10 non-null     int64  
 1   Column2  10 non-null     float64
 2   Column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [77]:
df3.shape

(10, 3)

In [78]:
df3.columns

Index(['Column1', 'Column2', 'Column3'], dtype='object')

In [79]:
df3.index

RangeIndex(start=0, stop=10, step=1)

## Viewing data from data frame

In [81]:
df3.head() #first 5 rows

Column1  Column2 Column3
0        1      1.2       a
1        2      1.3       b
2        3      1.4       c
3        4      2.5       d
4        5      2.3       e

In [82]:
df3.tail() #last 5 rows

Column1  Column2 Column3
5        6      4.1       f
6        7     23.2       g
7        8     12.4       h
8        9     21.3       i
9       10     23.6       j

In [84]:
df3.sample() #random

Column1  Column2 Column3
1        2      1.3       b

In [85]:
#for n random samples use sample(n)
df3.sample(3)

Column1  Column2 Column3
6        7     23.2       g
2        3      1.4       c
1        2      1.3       b

In [86]:
df3.describe()

Column1    Column2
count  10.00000  10.000000
mean    5.50000   9.330000
std     3.02765   9.807033
min     1.00000   1.200000
25%     3.25000   1.625000
50%     5.50000   3.300000
75%     7.75000  19.075000
max    10.00000  23.600000

In [91]:
# Renaming column names
df3=df3.rename(columns={"Column1":"First"})
df3

First  Column2 Column3
0      1      1.2       a
1      2      1.3       b
2      3      1.4       c
3      4      2.5       d
4      5      2.3       e
5      6      4.1       f
6      7     23.2       g
7      8     12.4       h
8      9     21.3       i
9     10     23.6       j